=begin
#Retrotax TCID

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2017-03-07T10:58:26Z

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module SwaggerClient

  class DocumentsInner
    # The document code used by the API. This field is used to identify the type of document and shall be used while uploading the document using the POST method.
    attr_accessor :code

    # The description of the document which details what is expected for this document.
    attr_accessor :description

    # The status of the document for this employee. There will be three possible statuses. missing | pending | approved. Status missing indicates that the document is not yet uploaded. Pending indicates that the document has been uploaded by the hiring manager/employee and is under review by the Retrotax Staff. Approved indicates that the document has been uploaded by the hiring manager/employee and approved by the Retrotax Staff
    attr_accessor :status

    # The link to access the uploaded document. If the status is missing, then this field shall be null.
    attr_accessor :document_url

    attr_accessor :thumbnail_urls

    # Link to the PDF Sample of the document.
    attr_accessor :pdf_sample

    # Link to the Image Sample of the document.
    attr_accessor :image_sample

    # The help section for the client to make understable about document.
    attr_accessor :client_help_text


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'code' => :'code',
        :'description' => :'description',
        :'status' => :'status',
        :'document_url' => :'document_url',
        :'thumbnail_urls' => :'thumbnail_urls',
        :'pdf_sample' => :'pdf_sample',
        :'image_sample' => :'image_sample',
        :'client_help_text' => :'client_help_text'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'code' => :'String',
        :'description' => :'String',
        :'status' => :'String',
        :'document_url' => :'String',
        :'thumbnail_urls' => :'DocumentsInnerThumbnailUrls',
        :'pdf_sample' => :'String',
        :'image_sample' => :'String',
        :'client_help_text' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'code')
        self.code = attributes[:'code']
      else
        self.code = "FORM A"
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = "New Employee Form A"
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = "missing"
      end

      if attributes.has_key?(:'document_url')
        self.document_url = attributes[:'document_url']
      else
        self.document_url = ""
      end

      if attributes.has_key?(:'thumbnail_urls')
        self.thumbnail_urls = attributes[:'thumbnail_urls']
      end

      if attributes.has_key?(:'pdf_sample')
        self.pdf_sample = attributes[:'pdf_sample']
      else
        self.pdf_sample = ""
      end

      if attributes.has_key?(:'image_sample')
        self.image_sample = attributes[:'image_sample']
      else
        self.image_sample = ""
      end

      if attributes.has_key?(:'client_help_text')
        self.client_help_text = attributes[:'client_help_text']
      else
        self.client_help_text = ""
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          code == o.code &&
          description == o.description &&
          status == o.status &&
          document_url == o.document_url &&
          thumbnail_urls == o.thumbnail_urls &&
          pdf_sample == o.pdf_sample &&
          image_sample == o.image_sample &&
          client_help_text == o.client_help_text
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [code, description, status, document_url, thumbnail_urls, pdf_sample, image_sample, client_help_text].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
